spring:
  application:
    name: payment-service
  datasource:
    url: jdbc:postgresql://localhost:5433/orders
    username: asik
    password: asik
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 8050
