spring:
  application:
   name: order-service
  datasource:
    url: jdbc:postgresql://localhost:5433/orders
    username: asik
    password: asik
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
  kafka:
    consumer:
      group-id: order-service-group
    bootstrap-servers: localhost:9092

server:
  port: 8040

payment-service:
  base-url: http://localhost:8050

order-paid-topic: orders.events
delivery-assigned-topic: delivery.events